# SPDX-FileCopyrightText: Alice Frosi <afrosi@redhat.com>
# SPDX-FileCopyrightText: Jakob Naucke <jnaucke@redhat.com>
#
# SPDX-License-Identifier: CC0-1.0

ARG build_type
FROM ghcr.io/confidential-clusters/buildroot AS builder
ARG build_type
WORKDIR /compute-pcrs

COPY Cargo.toml Cargo.lock .
COPY lib lib
COPY compute-pcrs/Cargo.toml compute-pcrs/
COPY compute-pcrs/src/lib.rs compute-pcrs/src/

# Set only required crates as members to minimize rebuilds upon changes.
# Build dependencies in lower layer to make use of caching.
RUN sed -i 's/members =.*/members = ["compute-pcrs", "lib"]/' Cargo.toml && \
    git clone --depth 1 https://github.com/confidential-clusters/reference-values && \
    cargo build -p compute-pcrs --lib $(if [ "$build_type" = release ]; then echo --release; fi)

COPY compute-pcrs/src compute-pcrs/src
RUN cargo build -p compute-pcrs $(if [ "$build_type" = release ]; then echo --release; fi)

FROM quay.io/fedora/fedora:45
ARG build_type
COPY --from=builder "/compute-pcrs/target/$build_type/compute-pcrs" /usr/bin
COPY --from=builder /compute-pcrs/reference-values /reference-values
